### ISSUE TITLE
big GC

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dzavalishin/phantomuserland#129]
```
start writing using max's snap checker?

must release locked (such that had disk read weerors and was cleared and locked 
out with mem unmap) objects too. such objects must be listed in special root 
list (kernel must unmap 'em enumerating that list). so such root list of broken 
objects must be treated as weak refs by GC - if no other references to broken 
space exist, such space can be reclaimed and removed from list


```

Original issue reported on code.google.com by `dmitry.zavalishin@gmail.com` on 19 Sep 2011 at 2:10

**Comment by dzavalishin** [comment]
memory size needed? disk back? can write to snap? have some bitmaps or maps<addr,state> to track progress so that we do not need to modify original snapshot?

possible solution - have it implemented in VM. need some read snap interface then.

classes: snap_list, snapshot, snapshot.read_object_header( vaddr, out header )

see #183 also - delete old snap - do it here too?

NB! need some way to request disk io barrier from here

**Comment by dzavalishin** [comment]
Write in Java, in a portable way. Run outside of Phantom on phantom disk image and inside of Phantom through special snapshot access class
